### ISSUE TITLE
Xbox 360 Controller not found

### ISSUE THREAD

**Issue by YopSolo** [zeh/key-action-binder#10]
i have this message in the console
------------------------
Error! Gamepad definition not found for GameInputDevice [Xbox 360 Controller (XInput STANDARD GAMEPAD)]!
Data about this controller needs to be added to controller.json.
Please read: https://github.com/zeh/key-action-binder#Contributing
------------------------

in the json file i see :
"os"				: ["Windows 7"],

is it because i am running this lib on windows 8.1 ?

**Comment by YopSolo** [comment]
have tested here
http://hosted.zehfernando.com/key-action-binder/tester/

![image](https://cloud.githubusercontent.com/assets/1012515/6432842/3823486e-c060-11e4-88c7-3bc8ba71abf2.png)

**Comment by zeh** [comment]
Hey YopSolo,

Yeah, that's probably the reason. Can you change that line in the JSON to

"os" : ["Windows 7", "Windows 8"],

And see if it works? (I haven't been able to confirm it yet, hence why I haven't changed it)

**Comment by cldme** [comment]
Hi, I have a small problem. I tried to test out the KeyActionBinder to see if my joystick is actually recognized. After I placed all the classes in the right spot (with the right path) I get these errors in the console:

keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 599	1119: Access of possibly undefined property id through a reference with static type flash.ui:GameInputControl.
keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 601	1119: Access of possibly undefined property minValue through a reference with static type flash.ui:GameInputControl.
keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 609	1119: Access of possibly undefined property minValue through a reference with static type flash.ui:GameInputControl.
keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 609	1119: Access of possibly undefined property maxValue through a reference with static type flash.ui:GameInputControlkeyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 640	1119: Access of possibly undefined property DEVICE_UNUSABLE through a reference with static type Class.

Can you please help me, because I can not find what I'm doing wrong. Thanks !

**Comment by zeh** [comment]
Hey,

It seems like it's trying to use the GameInputControl classes - the
built-in controller classes - and they're not being found.

Be sure you're exporting to an Air/Flash version that supports the gamepad
controls (swf target version should be around 12 or so, -target-player
should be about 23 or higher). Ditto for Flash Player, has to be 12.0 or
higher.

**Comment by zeh** [comment]
Closed this as duplicate.
